# Generated by Django 4.1.7 on 2023-12-09 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_image_shippingaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='senha',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
