# Generated by Django 5.0 on 2023-12-10 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_customer_senha"),
    ]

    operations = [
        migrations.AddField(
            model_name="product", name="estoque", field=models.IntegerField(default=0),
        ),
    ]
