version: "3.9"
services:
    app:
        build: .
        ports:
            - "8000:8000"
        image: ecomerce:django
        command: bash -c "dockerize -wait tcp://mysqldb:3306 -timeout 120s && python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
        volumes:
            - .:/app
        depends_on:
            - mysqldb
        environment: 
          - DJANGO_SUPERUSER_USERNAME=admin
          - DJANGO_SUPERUSER_PASSWORD=admin
          - DJANGO_SUPERUSER_EMAIL=admin@admin.com

    mysqldb:
        image: mysql:8.0
        ports:
            - "3307:3306"
        environment:
            MYSQL_DATABASE: 'appdb'
            MYSQL_PASSWORD: 'root'
            MYSQL_ROOT_PASSWORD: 'root'
        volumes:
            - ./mysql-data:/var/lib/mysql

